name: Continuous Integration

on:
  pull_request: null
  push:
    branches:
      - "0.x"

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: 7.2
            symfony-version: 4.4.*
          - php-version: 7.4
            symfony-version: 4.4.*
          - php-version: 7.2
            symfony-version: 5.1.*
          - php-version: 7.4
            symfony-version: 5.1.*

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.0.0

      - name: "Install dependencies with composer"
        run: |
          composer require --no-update "symfony/console:${SYMFONY_VERSION}"
          composer require --no-update "symfony/filesystem:${SYMFONY_VERSION}"
          composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"
          composer require --no-update "symfony/process:${SYMFONY_VERSION}"
          composer require --no-update "symfony/serializer:${SYMFONY_VERSION}"
          composer require --no-update "symfony/validator:${SYMFONY_VERSION}"
          composer update --no-interaction --no-progress --no-suggest

      - name: "Run checkstyle with squizlabs/php_codesniffer"
        run: vendor/bin/phpcs

      - name: "Run tests with phpunit/phpunit"
        run: vendor/bin/phpunit
