name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"

        dependencies:
          - "lowest"
          - "highest"

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Install lowest dependencies with composer
      if: "matrix.dependencies == 'lowest'"
      run: composer update --no-interaction --no-progress --no-suggest --prefer-lowest

    - name: Install highest dependencies with composer
      if: "matrix.dependencies == 'highest'"
      run: composer update --no-interaction --no-progress --no-suggest

    - name: "Run tests with phpunit/phpunit"
      run: vendor/bin/phpunit
