name: 'Lock down Pull Requests'

on:
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          close-pr: true
          lock-pr: true
          pr-comment: >
            Thanks for your pull request!

            However, this repository does not accept pull requests,
            see the README for details.

            If you want to contribute,
            you should instead open a pull request on the main repository:

            https://github.com/yokai-php/batch-src

            Thank you
